// apps/admin/src/app/login/page.tsx
"use client";
import React from "react";

export default function AdminLogin(): JSX.Element {
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [remember, setRemember] = React.useState(true);
  const [twofa, setTwofa] = React.useState("");
  const [error, setError] = React.useState("");
  const [busy, setBusy] = React.useState(false);
  const apiBase = React.useMemo(()=>{
    if (typeof window !== 'undefined' && window.location.hostname.endsWith('onrender.com')) return 'https://jeeeyai.onrender.com';
    return 'http://localhost:4000';
  }, []);

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    try {
      setBusy(true);
      const res = await fetch(`${apiBase}/api/admin/auth/login`, {
        method: 'POST',
        headers: { 'content-type':'application/json' },
        credentials: 'include',
        body: JSON.stringify({ email, password, remember, twoFactorCode: twofa })
      });
      if (!res.ok) {
        const j = await res.json().catch(()=>({error:'login_failed'}));
        setError(j.error || 'فشل تسجيل الدخول');
        return;
      }
      const params = new URLSearchParams(window.location.search);
      const redirectTo = params.get('next') || '/';
      window.location.href = redirectTo;
    } catch {
      setError('خطأ غير متوقع');
    } finally {
      setBusy(false);
    }
  }

  return (
    <main style={{ display:'grid', placeItems:'center', minHeight:'100vh', background:'#0b0e14', padding:24 }}>
      <form onSubmit={onSubmit} style={{ width:360, background:'#0f1420', border:'1px solid #1c2333', borderRadius:12, padding:16, color:'#e2e8f0' }}>
        <h1 style={{ margin:0, marginBottom:12, fontSize:20 }}>تسجيل دخول الإدارة</h1>
        <label style={{ display:'grid', gap:6, marginBottom:10 }}>البريد الإلكتروني
          <input value={email} onChange={(e)=>setEmail(e.target.value)} required style={{ padding:10, borderRadius:8, background:'#0b0e14', border:'1px solid #1c2333', color:'#e2e8f0' }} />
        </label>
        <label style={{ display:'grid', gap:6, marginBottom:10 }}>كلمة المرور
          <input type="password" value={password} onChange={(e)=>setPassword(e.target.value)} required style={{ padding:10, borderRadius:8, background:'#0b0e14', border:'1px solid #1c2333', color:'#e2e8f0' }} />
        </label>
        <label style={{ display:'grid', gap:6, marginBottom:10 }}>رمز 2FA (إن وُجد)
          <input value={twofa} onChange={(e)=>setTwofa(e.target.value)} placeholder="123456" style={{ padding:10, borderRadius:8, background:'#0b0e14', border:'1px solid #1c2333', color:'#e2e8f0' }} />
        </label>
        <label style={{ display:'flex', alignItems:'center', gap:8, marginBottom:10 }}>
          <input type="checkbox" checked={remember} onChange={(e)=>setRemember(e.target.checked)} /> تذكّرني (30 يومًا)
        </label>
        {error && <div style={{ marginBottom:10, color:'#f87171' }}>{error}</div>}
        <button type="submit" disabled={busy} style={{ width:'100%', padding:'10px 12px', background:'#800020', color:'#fff', borderRadius:8 }}>{busy? 'جارٍ الدخول...' : 'دخول'}</button>
      </form>
    </main>
  );
}

// apps/mweb/src/pages/Login.vue
<template>
  <div>
    <HeaderBar />
    <div class="container">
      <h1 style="margin:12px 0">تسجيل الدخول</h1>
      <form class="card space-y-12" @submit.prevent="onSubmit">
        <input v-model="email" type="email" placeholder="البريد الإلكتروني" class="input" style="height:44px;border-radius:12px;border:1px solid var(--muted-2);padding:0 12px" required />
        <input v-model="password" type="password" placeholder="كلمة المرور" class="input" style="height:44px;border-radius:12px;border:1px solid var(--muted-2);padding:0 12px" required />
        <button class="btn" style="width:100%">دخول</button>
        <div v-if="msg" class="badge" :class="{ ok: ok, err: !ok }">{{ msg }}</div>
        <div style="display:flex;justify-content:space-between"><a href="/register">إنشاء حساب</a><a href="/forgot">نسيت كلمة المرور؟</a></div>
      </form>
    </div>
    <BottomNav />
  </div>
</template>

<script setup lang="ts">
import HeaderBar from '@/components/HeaderBar.vue'
import BottomNav from '@/components/BottomNav.vue'
import { ref } from 'vue'
import { API_BASE } from '@/lib/api'
import { useUser } from '@/store/user'
import { useRouter } from 'vue-router'

const email = ref('admin@example.com')
const password = ref('admin123')
const msg = ref('')
const ok = ref(false)
const user = useUser()
const router = useRouter()

async function onSubmit(){
  msg.value=''; ok.value=false
  try{
    const res = await fetch(`${API_BASE}/api/admin/auth/login`, { method:'POST', headers:{ 'content-type':'application/x-www-form-urlencoded' }, body: new URLSearchParams({ email: email.value, password: password.value }) as any, credentials:'include' })
    ok.value = res.ok
    msg.value = res.ok ? 'تم تسجيل الدخول' : 'فشل تسجيل الدخول'
    if (res.ok) {
      user.isLoggedIn = true
      user.username = email.value.split('@')[0] || 'jeeey'
      router.replace('/account')
    }
  }catch{ msg.value='خطأ في الاتصال' }
}
</script>
