// apps/web/src/app/(auth)/login/page.tsx
// New login page
"use client";
import React from 'react';
import { trpc } from "../../providers";

export default function LoginPage(): JSX.Element {
  const rpc: any = trpc as any;
  const login = rpc.auth.login.useMutation();
  const [email, setEmail] = React.useState("");
  const [password, setPassword] = React.useState("");
  const [error, setError] = React.useState<string | null>(null);

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    try {
      await login.mutateAsync({ email, password });
      // After successful login, link anonymous session to user for analytics continuity (best-effort)
      try{
        const sid = typeof window!=='undefined'? (localStorage.getItem('sid_v1')||'') : '';
        if (sid){
          await fetch('/api/analytics/link', { method:'POST', headers:{ 'content-type':'application/json' }, credentials:'include', body: JSON.stringify({ sessionId: sid }) });
        }
      }catch{}
      const dest = new URL('/account', window.location.origin).toString();
      window.location.assign(dest);
    } catch (e: any) {
      setError(e?.message || "فشل تسجيل الدخول");
    }
  };

  return (
    <main className="min-h-screen p-4 max-w-sm mx-auto flex items-center">
      <form onSubmit={onSubmit} className="w-full border rounded p-4 space-y-3 bg-white">
        <h1 className="text-xl font-bold mb-1">تسجيل الدخول</h1>
        {error && <div className="text-sm text-red-600">{error}</div>}
        <input type="email" value={email} onChange={(e)=> setEmail(e.target.value)} placeholder="البريد الإلكتروني" className="w-full border rounded px-3 py-2 focus:border-[#800020]" required />
        <input type="password" value={password} onChange={(e)=> setPassword(e.target.value)} placeholder="كلمة المرور" className="w-full border rounded px-3 py-2 focus:border-[#800020]" required />
        <button type="submit" className="w-full px-4 py-2 bg-[#800020] text-white rounded">دخول</button>
        <div className="text-sm text-center">
          ليس لديك حساب؟ <a href="/register" className="text-[#800020] underline">إنشاء حساب</a>
        </div>
      </form>
    </main>
  );
}

// apps/mweb/src/pages/Login.vue
<template>
  <div>
    <HeaderBar />
    <div class="container">
      <h1 style="margin:12px 0">تسجيل الدخول</h1>
      <form class="card space-y-12" @submit.prevent="onSubmit">
        <input v-model="email" type="email" placeholder="البريد الإلكتروني" class="input" style="height:44px;border-radius:12px;border:1px solid var(--muted-2);padding:0 12px" required />
        <input v-model="password" type="password" placeholder="كلمة المرور" class="input" style="height:44px;border-radius:12px;border:1px solid var(--muted-2);padding:0 12px" required />
        <button class="btn" style="width:100%">دخول</button>
        <div v-if="msg" class="badge" :class="{ ok: ok, err: !ok }">{{ msg }}</div>
        <div style="display:flex;justify-content:space-between"><a href="/register">إنشاء حساب</a><a href="/forgot">نسيت كلمة المرور؟</a></div>
      </form>
    </div>
    <BottomNav />
  </div>
</template>

<script setup lang="ts">
import HeaderBar from '@/components/HeaderBar.vue'
import BottomNav from '@/components/BottomNav.vue'
import { ref } from 'vue'
import { API_BASE } from '@/lib/api'
import { useUser } from '@/store/user'
import { useRouter } from 'vue-router'

const email = ref('admin@example.com')
const password = ref('admin123')
const msg = ref('')
const ok = ref(false)
const user = useUser()
const router = useRouter()

async function onSubmit(){
  msg.value=''; ok.value=false
  try{
    const res = await fetch(`${API_BASE}/api/admin/auth/login`, { method:'POST', headers:{ 'content-type':'application/x-www-form-urlencoded' }, body: new URLSearchParams({ email: email.value, password: password.value }) as any, credentials:'include' })
    ok.value = res.ok
    msg.value = res.ok ? 'تم تسجيل الدخول' : 'فشل تسجيل الدخول'
    if (res.ok) {
      user.isLoggedIn = true
      user.username = email.value.split('@')[0] || 'jeeey'
      router.replace('/account')
    }
  }catch{ msg.value='خطأ في الاتصال' }
}
</script>
