// packages/ui/src/ProductCard.tsx
import React from 'react';
import { Button } from './Button';

interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  images: string[];
  stock: number;
  rating?: number;
  reviewCount?: number;
  oldPrice?: number;
  discountPct?: number;
  isWishlisted?: boolean;
}

interface ProductCardProps {
  product: Product;
  onAddToCart?: (productId: string) => void;
  onViewDetails?: (productId: string) => void;
  onToggleWishlist?: (productId: string) => void;
  className?: string;
}

export const ProductCard: React.FC<ProductCardProps> = ({
  product,
  onAddToCart,
  onViewDetails,
  onToggleWishlist,
  className = '',
}) => {
  const {
    id,
    name,
    price,
    images,
    stock,
    oldPrice,
    discountPct,
    isWishlisted,
  } = product;

  const mainImage = images[0] || '/images/placeholder-product.jpg';
  const isOutOfStock = stock <= 0;

  const formatPrice = (value: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);

  return (
    <div className={`bg-white rounded-xl border overflow-hidden transition-colors ${className}`}>
      {/* Image */}
      <div className="relative w-full aspect-[3/4] bg-gray-100">
        <img
          src={mainImage}
          alt={name}
          className="absolute inset-0 w-full h-full object-cover"
          onError={(e) => {
            const target = e.target as HTMLImageElement;
            target.onerror = null;
            target.src = '/images/placeholder-product.jpg';
          }}
        />
        {!!discountPct && (
          <div className="absolute left-2 top-2 text-[11px] px-2 py-1 rounded-full bg-[#800020] text-white">-{discountPct}%</div>
        )}
        <button
          aria-label="wishlist"
          className={`absolute right-2 top-2 text-[18px] ${isWishlisted ? 'text-[#800020]' : 'text-white'} drop-shadow`}
          onClick={(e)=>{ e.preventDefault(); onToggleWishlist?.(id); }}
        >
          {isWishlisted ? '❤' : '♡'}
        </button>
        {isOutOfStock && (
          <div className="absolute right-2 bottom-2 text-[11px] px-2 py-1 rounded-full bg-black/70 text-white">غير متوفر</div>
        )}
      </div>
      {/* Info */}
      <div className="p-2">
        <button
          className="block text-right w-full"
          onClick={() => onViewDetails?.(id)}
          aria-label={`view-${id}`}
        >
          <div className="text-[12px] text-gray-700 line-clamp-2 leading-snug">{name}</div>
          <div className="mt-1 flex items-center gap-2">
            <div className="text-[13px] font-bold text-[#800020]">{formatPrice(price)}</div>
            {!!oldPrice && oldPrice > price && (
              <div className="text-[11px] text-gray-400 line-through">{formatPrice(oldPrice)}</div>
            )}
          </div>
        </button>
      </div>
    </div>
  );
};

// apps/mweb/src/components/ProductCard.vue
<template>
  <a :href="href" class="product-card block relative bg-white border border-gray-100 rounded-lg overflow-hidden transition-shadow hover:shadow-md" @click.prevent="onClick">
    <div class="relative w-full pb-[133%] bg-gray-50">
      <img
        :src="thumb"
        :alt="title"
        class="absolute inset-0 w-full h-full object-cover"
        loading="lazy"
      />
      <div v-if="discountPercent" class="absolute top-2 right-2 bg-red-600 text-white text-[10px] font-bold px-1.5 py-0.5 rounded">
        -{{ discountPercent }}%
      </div>
    </div>
    <div class="p-2">
      <div class="text-[13px] text-gray-800 leading-tight line-clamp-2 h-9 mb-1">
        {{ title }}
      </div>
      <div class="flex items-center gap-2">
        <span class="font-bold text-black">{{ displayPrice }}</span>
        <span v-if="origPrice" class="text-xs text-gray-400 line-through">{{ origPrice }}</span>
      </div>
    </div>
  </a>
</template>

<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  id: string
  title: string
  image?: string
  images?: string[]
  price: number | string
  basePrice?: number | string
  href?: string
  discountPercent?: number
}>()

const thumb = computed(() => {
  return (Array.isArray(props.images) && props.images[0]) || props.image || ''
})

const displayPrice = computed(() => Number(props.price || props.basePrice || 0).toLocaleString())
const origPrice = computed(() => {
  if (props.discountPercent) {
    const p = Number(props.price || props.basePrice || 0)
    return Math.floor(p / (1 - (props.discountPercent / 100))).toLocaleString()
  }
  return null
})

function onClick() {
  if (props.href) window.location.href = props.href
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
